name: CI

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
      - uses: actions/checkout@v2
      - run: go vet ./...
      - run: go build ./...
      - run: go test -race ./...
